
image: python:latest

before_script:
  - python --version ; pip --version  # For debugging
  - python -m venv venv
  - source venv/bin/activate

test:
  script:
    - pip install pytest
    - pytest

